## Load aur India Filter

In [2]:
import pandas as pd

df = pd.read_csv("C:/Users/hp/VR-PROJECTS/zomato-restaurant-analysis/data/zomato.csv",encoding="latin-1")
india = df[df['Country Code'] == 1].copy()
india.shape

(8652, 21)

## Cusines ke missing rows

In [6]:
india['Cuisines'].isnull().sum()
india = india.dropna(subset=['Cuisines'])

## Suspicious values check karo

In [8]:
print((india['Aggregate rating'] == 0).sum())

2139

In [9]:
print(india['Rating text'].value_counts())

Rating text
Average      3678
Not rated    2139
Good         1847
Very Good     692
Poor          180
Excellent     116
Name: count, dtype: int64

In [10]:
print((india['Average Cost for two'] == 0).sum())

9

In [12]:
print(india['Currency'].value_counts())

Currency
Indian Rupees(Rs.)    8652
Name: count, dtype: int64

In [23]:
india['is_rated'] = (india['Aggregate rating'] > 0).astype(int)
india['is_rated'].value_counts()

is_rated
1    6513
0    2139
Name: count, dtype: int64

In [25]:
india[india['Average Cost for two'] == 0][['Restaurant Name', 'City', 'Votes', 'Aggregate rating']]

                    Restaurant Name       City  Votes  Aggregate rating
634     The Latitude - Radisson Blu       Agra    103               3.9
637                 Sheroes Hangout       Agra     77               4.9
639                  Chapter 1 Cafe       Agra     98               3.9
677                  The BrewMaster  Allahabad     49               3.3
851            BMG - All Day Dining   Dehradun     63               4.3
2364  Atmosphere Grill Cafe Sheesha     Kanpur     34               3.6
2368                     UrbanCrave     Kanpur    127               3.9
9242             Deena Chat Bhandar   Varanasi     78               3.8
9254                VNS Live Studio   Varanasi    109               3.5

In [28]:
## cost ke autlier

india['Average Cost for two'].describe()
india.nlargest(5, 'Average Cost for two')[['Restaurant Name', 'City', 'Average Cost for two']]

,Restaurant Name,City,Average Cost for two
7543,Orient Express - Taj Palace Hotel,New Delhi,8000
4088,Tian - Asian Cuisine Studio - ITC Maurya,New Delhi,7000
4087,Bukhara - ITC Maurya,New Delhi,6500
7492,Nostalgia at 1911 Brasserie - The Imperial,New Delhi,6000
7494,1911 - The Imperial,New Delhi,6000

In [46]:
raw = pd.read_csv("C:/Users/hp/VR-PROJECTS/zomato-restaurant-analysis/data/zomato.csv",encoding="latin-1")
print(raw['Has Table booking'].unique())
print(raw['Has Online delivery'].unique())

['Yes' 'No']
['No' 'Yes']

## Yes/No ko (0/1)

In [51]:
for col in ['Has Table booking','Has Online delivery']:
    india[col] = raw.loc[india.index, col].map({'Yes':1, 'No':0})

print(india['Has Table booking'].value_counts(dropna=False))
print(india['Has Online delivery'].value_counts(dropna=False))

Has Table booking
0    7541
1    1111
Name: count, dtype: int64
Has Online delivery
0    6229
1    2423
Name: count, dtype: int64

In [53]:
india.columns.tolist()

['Restaurant ID',
 'Restaurant Name',
 'City',
 'Address',
 'Locality',
 'Locality Verbose',
 'Longitude',
 'Latitude',
 'Cuisines',
 'Average Cost for two',
 'Has Table booking',
 'Has Online delivery',
 'Is delivering now',
 'Price range',
 'Aggregate rating',
 'Rating text',
 'Votes',
 'is_rated']

## Unnecessary columns hatao

In [42]:
cols_to_drop = ['Switch to order menu', 'Rating color','Country Code', 'Currency']
india = india.drop(columns=cols_to_drop, errors='ignore')

## Cuisines ko tod kar alag table banao

In [54]:
cuisines = india[['Restaurant ID', 'Cuisines']].copy()
cuisines['Cuisines'] = cuisines['Cuisines'].str.split(", ")
cuisines = cuisines.explode('Cuisines')

In [55]:
print(india.shape)

(8652, 18)

In [56]:
print(india['Has Table booking'].value_counts(dropna=False))
print(india['Has Online delivery'].value_counts(dropna=False))

Has Table booking
0    7541
1    1111
Name: count, dtype: int64
Has Online delivery
0    6229
1    2423
Name: count, dtype: int64

In [57]:
print((india['Average Cost for two'] == 0).sum())

9

## Clean Data Save

In [58]:
india.to_csv("C:/Users/hp/VR-PROJECTS/zomato-restaurant-analysis/data/zomato_india_clean.csv",index=False)
cuisines.to_csv("C:/Users/hp/VR-PROJECTS/zomato-restaurant-analysis/data/zomato_cuisines.csv",index=False)